# Generated by Django 3.2.3 on 2021-10-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OURDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location_DB', models.CharField(max_length=45)),
                ('Count_num', models.IntegerField()),
                ('Helmet_num', models.IntegerField()),
                ('vehicle_type', models.IntegerField()),
                ('personal_ID', models.CharField(max_length=45)),
                ('vehicle_number', models.CharField(max_length=45)),
                ('phone_num', models.CharField(max_length=45)),
            ],
        ),
    ]
