# Generated by Django 3.2.8 on 2021-10-25 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211016_1157'),
        ('blog', '0002_ourdb'),
    ]

    operations = [
    ]
