# Generated by Django 3.2.8 on 2021-11-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_merge_0002_auto_20211016_1157_0002_ourdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='OURDB',
        ),
        migrations.AlterField(
            model_name='carnumber',
            name='carnumber',
            field=models.CharField(max_length=20),
        ),
    ]
