# Generated by Django 3.2.8 on 2021-11-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_graph'),
    ]

    operations = [
        migrations.DeleteModel(
            name='graph',
        ),
        migrations.AddField(
            model_name='carnumber',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
